#!/usr/bin/env bash

set -euo pipefail

script_dir="$(dirname "${0}")"
if [[ ! -d "${script_dir}/.venv" ]]; then
    python3 -m venv "${script_dir}/.venv"
fi
source "${script_dir}/.venv/bin/activate"
pip3 install optuna
"${script_dir}/tune_network.py"
rm -rf "${script_dir}/.venv"

