#!/usr/bin/env bash

set -euo pipefail

usage() {
    echo "Usage: compile [build_type(Release|Debug|RelWithDebInfo)]"
    echo "Build type defaults to Release"
}

if [[ $# -ge 2 ]]; then
    usage >&2
    exit 1
fi

cpus=8
if command -v nproc &>/dev/null; then
    cpus="$(nproc)"
fi
build_type=Release
if [[ $# -eq 1 ]]; then
    if [[ "${1}" == -h ]] || [[ "${1}" == --help ]]; then
        usage
        exit 0
    fi
    if [[ ! "${1}" =~ ^(Debug|Release|RelWithDebInfo)$ ]]; then
        usage >&2
        exit 1
    fi
    build_type="${1}"
fi

cmake --build "build_${build_type}" -- "-j${cpus}"
