#!/usr/bin/env bash

set -euo pipefail

usage() {
    echo "Usage compile [--cpu cpu_count] [--build-type <Release|RelWithDebInfo|Debug>]"
    echo "--build-type defaults to Release"
}

build_type=Release
cpus=8
if command -v nproc &>/dev/null; then
    cpus="$(nproc)"
fi
while [[ $# -gt 0 ]]; do
    case $1 in
    --build-type)
        build_type="$2"
        shift 2
        ;;
    --cpu)
        cpus="$2"
        shift 2
        ;;
    -h | --help)
        usage
        exit 0
        ;;
    *)
        usage >&2
        exit 1
        ;;
    esac
done
if [[ ! "${build_type}" =~ ^(Debug|RelWithDebInfo|Release)$ ]]; then
    usage >&2
    exit 1
fi

cmake --build "build_${build_type}" -- "-j${cpus}"
