#!/usr/bin/env bash

# Use this script to make sure that the build works, but not to build regularly

set -euo pipefail

usage() {
	echo "Usage: everything --build-type <Release|Debug> --cpus <number_of_cpus>"
}

build_type=Release
cpus=1

while [[ $# -gt 0 ]]; do
	case $1 in
	--build-type)
		build_type="$2"
		shift 2
		;;
	--cpus)
		cpus="$2"
		shift 2
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		usage >&2
		exit 1
		;;
	esac
done

if [[ ! "${build_type}" =~ ^(Debug|Release)$ ]]; then
	usage >&2
	exit 1
fi

if [[ -v VIRTUAL_ENV ]]; then
	deactivate || true
fi
git clean -fdx
python3 -m venv .venv
source .venv/bin/activate
pip install conan
./configure_build "${build_type}"
./run_build "${cpus}"
